version: '3.8'

services:
 db:
  container_name: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
  image: postgres:15.3-alpine3.18